apiVersion: v1
kind: Namespace
metadata:
  name: net-ingress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
  namespace: net-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo:1.0
        args:
        - "-text=hello"
        ports:
        - containerPort: 5678
