apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: ckad
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /workspaces/ckad/.cluster/mounts/data
    containerPath: /mnt/data
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        event-ttl: "8h0m0s"
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "127.0.0.1"
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "127.0.0.1"
  - containerPort: 30443
    hostPort: 30443
    listenAddress: "127.0.0.1"
- role: worker
  extraMounts:
  - hostPath: /workspaces/ckad/.cluster/mounts/data
    containerPath: /mnt/data
  extraPortMappings:
  - containerPort: 30000
    hostPort: 40000
    listenAddress: "127.0.0.1"
  - containerPort: 30080
    hostPort: 40080
    listenAddress: "127.0.0.1"
  - containerPort: 30443
    hostPort: 40443
    listenAddress: "127.0.0.1"
  labels:
    tier: frontend
- role: worker
  extraMounts:
  - hostPath: /workspaces/ckad/.cluster/mounts/data
    containerPath: /mnt/data
  extraPortMappings:
  - containerPort: 30000
    hostPort: 50000
    listenAddress: "127.0.0.1"
  - containerPort: 30080
    hostPort: 50080
    listenAddress: "127.0.0.1"
  - containerPort: 30443
    hostPort: 50443
    listenAddress: "127.0.0.1"
  labels:
    tier: backend


