apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-demo-blue
  namespace: blue-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-demo
      version: blue
  template:
    metadata:
      labels:
        app: blue-green-demo
        version: blue
    spec:
      containers:
      - name: app
        image: nginx:1.25
